# Generated by Django 5.1.1 on 2024-12-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_concessionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Admission'), ('3d', '3D Admission')], max_length=50)),
                ('showtime', models.CharField(choices=[('evening', 'Evening Show'), ('matinee', 'Matinee')], max_length=50)),
                ('age_group', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
