# Generated by Django 5.1.1 on 2024-12-19 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviePoster',
        ),
    ]
